# Generated by Django 5.0.2 on 2024-04-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_user_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
