# Generated by Django 5.0.2 on 2024-04-03 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
